title: Erfan Alimohammadi
description: in Persian "عرفان علی‌محمّدی"

social:
  - title: GitHub
    img: /assets/images/github.ico
    url: https://github.com/erfaniaa
  - title: Blog (in Persian)
    img: /assets/images/blog.png
    url: http://palindrome.ir
  - title: Twitter
    img: /assets/images/twitter.ico
    url: https://twitter.com/erfanafre
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:erfan.aa@gmail.com

avatar: /assets/images/avatar.jpg
introduction: >
  Hi! I'm Erfan Alimohammadi.<br/>
  This is my personal web page.<br/>

projects:
  title: Open Source Projects
  github:
    - Erfaniaa/text-to-commit-history
    - Erfaniaa/codes2pdf
    - Erfaniaa/map-coloring
    - Erfaniaa/Tweeterify
    - Erfaniaa/Codeforces
    - Erfaniaa/compilers-course-project
    - Erfaniaa/Persian-OCR
  content: >
    <p>Other projects that I have contributed can be found in <a href="https://github.com/Erfaniaa">github.com/Erfaniaa</a>.</p>

working:
  title: Related Profile Links
  timeline:
    - "<p><a href='https://erfaniaa.github.io/resume.pdf'>My resume</a></p>"
    - "<p><a href='https://linkedin.com/in/erfan-alimohammadi'>My LinkedIn profile</a></p>"
    - "<p><a href='https://icpc.baylor.edu/ICPCID/0X1FK464JA9X'>My ICPCID</a></p>"
    - "<p><a href='https://stackoverflow.com/users/2635857/erfan-alimohammadi'>My Stack Overflow profile</a></p>"

google_analytics: UA-145465443-1
